### ISSUE TITLE
Bottom bar overlap with the "Graph Space List" in Schema Tag of Studio 2.2.2

### ISSUE THREAD

**Issue by pengweisong** [vesoft-inc/nebula-studio#10]
**Describe the bug**

Bottom bar overlap with the "Graph Space List" in Schema Tag

**Environments**

* OS: Mac
* Node-version: `node --version` 
* Studio-version: 2.2.2

**How To Reproduce**
when there are too many spaces in the space list

**Expected behavior**

Bottom bar should not be overlapped with the space list.

**Additional context**

![image](https://user-images.githubusercontent.com/90180021/132467839-0e8ed952-72e6-44cf-a0d4-1b1e2fe6f09f.png)

**Comment by hetao92** [comment]
its fixed in v3.0.0
