### ISSUE TITLE
When I expand the vertex, the menu can't be displayed completely

### ISSUE THREAD

**Issue by Sophie-Xie** [vesoft-inc/nebula-studio#11]
**Describe the bug (__must be provided__)**

When I expand the vertex, the menu can't be displayed completely.

**Your Environments (__must be provided__)**

* OS: Mac 
* Node-version: 2.0.1
* Studio-version: 2.2.2

**How To Reproduce(__must be provided__)**

![image](https://user-images.githubusercontent.com/84560950/132502793-a95f99cc-88a3-46a7-87ee-882239e88de9.png)

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by hetao92** [comment]
fixed in #66
