### ISSUE TITLE
nebula web 显示问题

### ISSUE THREAD

**Issue by liangshuang110** [vesoft-inc/nebula-studio#118]
我想不用拓展直接显示全部点和边可以吗

**Comment by nianiaJR** [comment]
> 我想不用拓展直接显示全部点和边可以吗

目前设计的方向是用户推敲式的探索，如果直接显示全部点和边的话，可能在数据量比较庞大的情况下，造成页面卡死哦。

**Comment by nianiaJR** [comment]
探索的结果可以看做是逐步查询得来的，如果一次性全部把图画出来，可能需要单独来围绕这个需要来设计，甚至对于数据量比较大的情况，这种绘图可以看做是运行一次job.
