### ISSUE TITLE
Edit the graph while exploring

### ISSUE THREAD

**Issue by Mcontrite** [vesoft-inc/nebula-studio#130]
I think if we can modify the graph while exploring will be very convenient, such as create a new vertex or a new edge. In other ways, it's also good that we can only edit the data on them. These feature will provide much better user experiences.

**Comment by hetao92** [comment]
Thank you for your suggestion, we will consider whether to support this feature in the future, and it may be implemented first in nebula-explorer

**Comment by hetao92** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime. Thanks a lot for your understanding.
