### ISSUE TITLE
docker compose resource url 404

### ISSUE THREAD

**Issue by zhiwen95** [vesoft-inc/nebula-studio#140]
**Describe the bug (__must be provided__)**

https://oss-cdn.nebula-graph.com.cn/nebula-graph-studio/3.2.2/nebula-graph-studio-v3.2.2.tar.gz 404 in https://docs.nebula-graph.com.cn/3.0.0/nebula-studio/deploy-connect/st-ug-deploy/#docker_studio step 1

**Comment by wey-gu** [comment]
Thanks @zhiwen95 
We will fix this soon, please use https://github.com/vesoft-inc/nebula-studio/archive/refs/tags/v3.2.2.tar.gz instead first before it's fetchable first ;)

**Comment by hetao92** [comment]
fixed, you can download now
