### ISSUE TITLE
studio v3.3.0 beta suggestions

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-studio#151]
- [x] - favorite 功能太棒了👍🏻
- [x] - 请问 cypher parameter 应该咋用哈（支持这个太棒了！）？
- [x] - host 能不能在不填写端口的时候默认选择 9669？
- [x] - ~~console 里 能不能比如 command(mac)/ctrl(win/linux) + enter 是按 run 的效果?~~ 原来是 shift + enter! 👍🏻
- [x] - clear connection 能不能翻译成 log out/登出?
- [ ] - 在 console 里不能 use space 感觉稍微有点奇怪？
- [x] - explain format="dot" match (n:player) return n limit 10 ，点 graphviz 是空的 😭?
- [x] - bar 上的，英文下的字体感觉可以换一下哈 @yyh0808  图 1
- [ ] - schema 界面的 comment 要不要 把 _EMPTY_ 显示为空哈？
- [ ] - 导入界面，日志的字体可不可以比左边的文件名字体小一些？ @yyh0808  图 1
- [x] 导入的 csv 文件预览太赞了 👍🏻
- [x] 文档页特别赞 👍🏻 💯
- [x] New version 字段改成叫 release note 或者 What's New in this version?
- [ ] 能不能全屏一个 console 下边的 Graph?
- [ ] 能不能增加某种方式让点散开？图 2
- [x] console 结果导出图片

> 图 1
<img width="937" alt="Screen Shot 2022-03-18 at 12 03 41 PM" src="https://user-images.githubusercontent.com/1651790/158935341-f693386f-e66e-418f-848b-2c6d8015aca6.png">

> 图 2

<img width="1162" alt="Screen Shot 2022-03-18 at 12 19 45 PM" src="https://user-images.githubusercontent.com/1651790/158936805-b04fccb1-50da-4466-9780-6f0cbd900972.png">

**Comment by yyh0808** [comment]
@wey-gu navbar上，字体还没有打包，所以效果看着比较奇怪；日志这块会需要调整，我还没有review到这个页面，设计稿是比较小的

**Comment by wey-gu** [comment]
> @wey-gu navbar上，字体还没有打包，所以效果看着比较奇怪；日志这块会需要调整，我还没有review到这个页面，设计稿是比较小的

日志要是能来个关键词高亮就最好了 ;)

**Comment by hetao92** [comment]
cypher 参考 neo4j https://neo4j.com/docs/java-reference/current/java-embedded/query-parameters/

**Comment by wey-gu** [comment]
> cypher 参考 neo4j https://neo4j.com/docs/java-reference/current/java-embedded/query-parameters/

收到 👍🏻
