### ISSUE TITLE
最短路径操作是否可以在可视化界面直接操作，不要先在console执行命令再可视化展示？

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-studio#170]
https://github.com/vesoft-inc/nebula-web-docker/pull/169/files

这样的操作流程太过割裂了，这个console命令用explore也是可以拼装出来的。

**Comment by nianiaJR** [comment]
这个可以的，目前的流程开始来是 Console -> Explore 的便捷操作，我们单独在Explore交互下增强下探索的选择：子图，应该就ok了，相当于增强Explore本身的图探索功能，两者我理解都应该存在。

**Comment by whitewum** [comment]
是的。

**Comment by nianiaJR** [comment]
嗯，这个找时间加一下，预计在2.0连接兼容以后吧🤝

**Comment by hetao92** [comment]
fixed in explorer
