### ISSUE TITLE
issues handling importing csv with date typed fields

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-studio#172]
**Describe the bug (__must be provided__)**

It seems when a field with type date was configured in the studio, with a field like `2020-01-01` in CSV, it will fail.
Whereas in importer, it should be working:

--------------
https://github.com/vesoft-inc/nebula-importer/blob/617990914cfe30a906351f3eb2f7ca697555dfd4/examples/v2/example.yaml#L415-L435

https://github.com/vesoft-inc/nebula-importer/blob/master/examples/v2/date_test.csv

**Your Environments (__must be provided__)**

* OS: Linux,Mac or Windows
* Node-version: `node --version` 
* Studio-version: v3.2.3

**How To Reproduce(__must be provided__)**

1. Step 1 create schema like
<img width="1656" alt="Screen Shot 2022-04-01 at 10 14 25 AM" src="https://user-images.githubusercontent.com/1651790/161181165-e4cf651b-84cd-44cd-b7f4-7556363793e6.png">

2. Step 2 prepare data like
```csv
"v1",2020-01-01
"v2",2020-01-02
```
3. Step 3 import like
<img width="1777" alt="Screen Shot 2022-04-01 at 10 15 23 AM" src="https://user-images.githubusercontent.com/1651790/161181277-4f770598-50a3-4308-8cad-5e26646b7779.png">

4. It failed as:
```
$ docker logs nebula-graph-studio-v323_web_1 --since 20m
[INFO] 2022/04/01 02:04 200 1.175753ms 192.168.9.3 PUT /api/files
[INFO] 2022/04/01 02:04 200 191.017µs 192.168.9.3 GET /api/files
[INFO] 2022/04/01 02:04 200 1.999393ms 192.168.9.3 POST /api-nebula/db/exec
[INFO] 2022/04/01 02:04 200 2.166102ms 192.168.9.3 POST /api-nebula/db/exec
[INFO] 2022/04/01 02:04 200 1.558106ms 192.168.9.3 POST /api-nebula/db/exec
1.6487787003726132e+09	warn	controller/gateway.go:56	gql execute fail	{"error": "-1005:Storage Error: The data type does not meet the requirements. Use the correct type of data."}
```

**Expected behavior**

Import successfully

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by hetao92** [comment]
we will fix this in v3.3.0
