### ISSUE TITLE
Supporting Parameterized Query in console

### ISSUE THREAD

**Issue by slimshadylol0303** [vesoft-inc/nebula-studio#174]

**Comment by wey-gu** [comment]
It's actually supported already:

<img width="1562" alt="Screen Shot 2022-04-03 at 12 49 25 AM" src="https://user-images.githubusercontent.com/1651790/161392977-98f4aec7-8e80-413e-87d2-b8482e5e26fb.png">

<img width="1562" alt="Screen Shot 2022-04-03 at 12 50 03 AM" src="https://user-images.githubusercontent.com/1651790/161393000-5de58384-368f-4d7e-ac51-fa18dedc27d9.png">
