### ISSUE TITLE
查询使用了关键字的标签属性时，具体页面会提示tag不存在但是预览是会有属性

### ISSUE THREAD

**Issue by wxai2324** [vesoft-inc/nebula-studio#19]
使用版本 Nebula Graph Studio 3.0.0

比如我使用了TEXT 作为TAG时
预览会显示相关属性
![image](https://user-images.githubusercontent.com/18702381/135214757-85bf49fa-7d2b-453c-9671-c0f2703e71e3.png)

但是当我进行属性修改时就会提示我
![image](https://user-images.githubusercontent.com/18702381/135214844-7f7785a6-35a3-47d7-b5a0-e09b69d8a35e.png)
导致我无法在可视化界面修改该TAG（也无法删除），只能通过命令。
另外在图探索界面也是，如果我的关系名称也是关键字的话就不能使用相关的关系进行查询，也会报错

**Comment by hetao92** [comment]
thanks for your reminder. it will be fixed in next version v3.1.0

**Comment by hetao92** [comment]
fixed
