### ISSUE TITLE
Nebula Studio 配置数据库闪退

### ISSUE THREAD

**Issue by nieyuan1980** [vesoft-inc/nebula-studio#193]
第1次使用Nebula Studio配置数据库连接不成功，有一个提示一闪而过，不知原因。
1.Nebula Studio 界面
![image](https://user-images.githubusercontent.com/25432482/104261430-806ccc80-54c0-11eb-8550-d58394bf8325.png)

2.Nebula 数据库状态
![image](https://user-images.githubusercontent.com/25432482/104261477-98dce700-54c0-11eb-8ba5-b60ac94da535.png)

**Comment by nianiaJR** [comment]
nebula是什么版本？

**Comment by nieyuan1980** [comment]
> nebula是什么版本？
请问怎样查看nebula版本？

**Comment by nianiaJR** [comment]
> > nebula是什么版本？
> > 请问怎样查看nebula版本？

如果你是docker启动的，`cat docker-compose.yml` 就能看到了

**Comment by nieyuan1980** [comment]
> > > nebula是什么版本？
> > > 请问怎样查看nebula版本？
> 
> 如果你是docker启动的，`cat docker-compose.yml` 就能看到了

![image](https://user-images.githubusercontent.com/25432482/104263974-9df06500-54c5-11eb-882b-87d1576cd60a.png)

**Comment by nianiaJR** [comment]
> > > > nebula是什么版本？
> > > > 请问怎样查看nebula版本？
> > 
> > 
> > 如果你是docker启动的，`cat docker-compose.yml` 就能看到了
> 
> ![image](https://user-images.githubusercontent.com/25432482/104263974-9df06500-54c5-11eb-882b-87d1576cd60a.png)

你的是nebula2.x版本，用了studio1.x来连接，肯定不行的，如果要用请使用studio2.x： https://github.com/vesoft-inc/nebula-web-docker/tree/master/v2

**Comment by nieyuan1980** [comment]
> > > > > nebula是什么版本？
> > > > > 请问怎样查看nebula版本？
> > > 
> > > 
> > > 如果你是docker启动的，`cat docker-compose.yml` 就能看到了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/25432482/104263974-9df06500-54c5-11eb-882b-87d1576cd60a.png)
> 
> 你的是nebula2.x版本，用了studio1.x来连接，肯定不行的，如果要用请使用studio2.x： https://github.com/vesoft-inc/nebula-web-docker/tree/master/v2

请问如何卸载studio1.x呢？

**Comment by nieyuan1980** [comment]
> > > > > nebula是什么版本？
> > > > > 请问怎样查看nebula版本？
> > > 
> > > 
> > > 如果你是docker启动的，`cat docker-compose.yml` 就能看到了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/25432482/104263974-9df06500-54c5-11eb-882b-87d1576cd60a.png)
> 
> 你的是nebula2.x版本，用了studio1.x来连接，肯定不行的，如果要用请使用studio2.x： https://github.com/vesoft-inc/nebula-web-docker/tree/master/v2

![image](https://user-images.githubusercontent.com/25432482/104319416-cb67fd80-551b-11eb-9a02-a0c48cf77165.png)

19%就一直没有进度了，还有其它方式吗？

**Comment by NicolaCage** [comment]
你好，问题有解决吗

**Comment by NicolaCage** [comment]
根据上述内容，你可以cd 今日nebula-web-docker的v2目录，执行docker-compose pull获取studio2.x镜像，然后启动使用再看看

**Comment by nieyuan1980** [comment]
放弃了。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vesoft-inc/nebula-web-docker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 下午2:02
收件人:&nbsp;"vesoft-inc/nebula-web-docker"<nebula-web-docker@noreply.github.com&gt;;
抄送:&nbsp;"缘来是渊"<nieyuan1980@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vesoft-inc/nebula-web-docker] Nebula Studio 配置数据库闪退 (#193)





 
根据上述内容，你可以cd 进入nebula-web-docker的v2目录，执行docker-compose pull获取studio2.x镜像，然后启动使用再看看
