### ISSUE TITLE
Request for support deployment on Kubernetes, yaml or helm.

### ISSUE THREAD

**Issue by matrixji** [vesoft-inc/nebula-studio#20]
**Is your feature request related to a problem? Please describe.**
As we have `nebula-operator`, currently we are already could deploy a nebula graph cluster on Kubernetes quickly. But still not possible to deploy `nebula-studio` directly on Kubernetes.

**Describe the solution you'd like**
A yaml or helm solution to deploy nebula-studio on Kubernetes:
- It supporting deploy studio/importer/http-gateway instances on different nodes with RWX Volume, or share data with object storage like S3 service.
- Support ingress controller for exporting studio's service endpoint

**Describe alternatives you've considered**
Maybe a simple transitional solution is using Infinity to deploy studio/importer/http-gateway in the same node with RWO Volume, and using NodePort to export service.

**Additional context**
None

**Comment by matrixji** [comment]
FYI: I've created a repository for sharing my helm chart about this feature: https://github.com/matrixji/nebula-studio-helm 

I'm not sure if it is suitable to contributing it as a sub-folder in this repository, if people want to deploy nebula-studio under Kubernetes, it could be a reference for starting.

**Comment by wey-gu** [comment]
Thank you @matrixji, amazing work!

This is for sure our missing pieces and maybe the helm is perfect for the stateless studio to enable unified(k8s infra only) studio deployment!!!

@MegaByte875 @nianiaJR could you kindly look into this? How could we collaborate with @matrixji to bringing this great convenience to the whole community? Help transfer the repo to the community or merge it into a subfolder of this repo/operator repo or submodule?

**Comment by jerryliang64** [comment]
OK，we‘ll test & check it.Thanks @matrixji 🌹

**Comment by hetao92** [comment]
Thank you for your contribution @matrixji 
We have tested the helm chart under your repository and it runs successfully. So you are welcome to submit pull request, after modifying some details, it can be used by more people

**Comment by matrixji** [comment]
> Thank you for your contribution @matrixji We have tested the helm chart under your repository and it runs successfully. So you are welcome to submit pull request, after modifying some details, it can be used by more people

Thanks for the feedback, I'll raise a PR to put it into a subfolder.
