### ISSUE TITLE
Failed to open transport, error: dial tcp X.X.X.X:9669: i/o timeout

### ISSUE THREAD

**Issue by lia-git** [vesoft-inc/nebula-studio#213]
when try to remote connect the nebula graph in Studio ,it occurs ,but I can connect to it  in reomte console in terminal

**Comment by lia-git** [comment]
![image](https://user-images.githubusercontent.com/8582254/111730009-64641d80-88ab-11eb-848a-baf70b153ad4.png)

**Comment by NicolaCage** [comment]
To follow up on our BBS https://discuss.nebula-graph.com.cn/t/topic/3198/10
