### ISSUE TITLE
关于 Studio 的 Session 过期问题的提议

### ISSUE THREAD

**Issue by ianhhhhhhhhe** [vesoft-inc/nebula-studio#214]
**Is your feature request related to a problem? Please describe.**

设置较短的 session 时间后，在一段时间未使用 studio 时，操作 studio 就会抛 Get sessionId[1652478801981921] failed 的问题

**Describe the solution you'd like**

如果此时 studio 收到了这个错误信息后，可以自动重新获取 session 或者自动跳转到 login 界面的话，体验会更好一点。

PS：Session 只有 SHOW SESSIONS 的功能，如果能出一个清理 Session 的命令就更好了

**Comment by hetao92** [comment]
Sorry for the late reply, thanks for your suggestion, it will be fixed in the next version

**Comment by hetao92** [comment]
it has been fixed in studio v3.4.0 and released
