### ISSUE TITLE
nebula-studio 查询点无显示

### ISSUE THREAD

**Issue by jackiesre721** [vesoft-inc/nebula-studio#215]
**Describe the bug (__must be provided__)**
当graphd节点内存占用超过80%时，查询已知点数据无显示，换到没有到达80%的点是可以显不的

**Your Environments (__must be provided__)**

*  CentOS 7
*  node 16.15.0 
* Studio-version: display in studio navBar

**How To Reproduce(__must be provided__)**

1. 通过nebula-studio在超过80%内存的机器上查询点无显示
2. 通过nebula-studio没超过80%内存的机器上查询点无显示

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by hetao92** [comment]
could you please open Chrome console to see if there is any error message, and if the interface returns data?
Btw, could you reproduce this by using nebula-console

**Comment by hetao92** [comment]
Due to no progress for a month, this issue is closed first, if you have a new update, you can open the issue again.
