### ISSUE TITLE
2.0 的string 可以支持 starts with 等其他操作，studio只允许 ==

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-studio#218]
![image](https://user-images.githubusercontent.com/50101159/112275826-feb4ce80-8cba-11eb-9504-2eafe87a07e5.png)

![image](https://user-images.githubusercontent.com/50101159/112276076-4176a680-8cbb-11eb-8686-e7d94f1bda8f.png)

**Comment by hetao92** [comment]
fixed in explorer
