### ISSUE TITLE
图探索对于vid int和string的支持有问题

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-studio#219]
![image](https://user-images.githubusercontent.com/50101159/112276449-b8ac3a80-8cbb-11eb-9baf-b1ffac33741e.png)

![image](https://user-images.githubusercontent.com/50101159/112276481-c2ce3900-8cbb-11eb-8bea-12cf2fe6aedb.png)

![image](https://user-images.githubusercontent.com/50101159/112276513-cc57a100-8cbb-11eb-8bed-de40ef7eb6ac.png)

我明明是 fixed_string ，为什么添加节点的时候，只能 用 int?

**Comment by hetao92** [comment]
fixed
