### ISSUE TITLE
Too many memory used while startup nebula-studio with container on server with lot's CPU core

### ISSUE THREAD

**Issue by matrixji** [vesoft-inc/nebula-studio#22]
**Describe the bug (__must be provided__)**

I using Kubernetes to start nebula-studio, and set limits with 2G memory, it always got OOM Killed on startup.
I then check with docker-compose way, it starts many node worker processes (depends how many CPU core's we have), as I using a server with 72cores, and each node work process may need about 50MB memory, so totally, it requires about 3.6GB memory, then I increase the memory limits in Kubernetes deployment, it's OK.

**Your Environments (__must be provided__)**

* OS: Linux
* Node-version: N/A using official container 
* Studio-version: official container image: `vesoft/nebula-graph-studio:v3`

**How To Reproduce(__must be provided__)**

It should be clear in the above description.

**Expected behavior**

I think at least for a startup there is no need for so many worker processes.
Maybe a suitable startup configuration `--workers=3` like a non-container startup is a simple solution.

Contents in file: package.json
```json
{
"start": "egg-scripts start --daemon --title=egg-server-nebula-graph-studio --workers=3",
"docker-start": "egg-scripts start --title=egg-server-nebula-graph-studio"
}
```

And if possible, we'd better calculate the worker's number, by checking below things under container:

- How many CPUs does the node has, from `nproc`
- How many logical CPUs avaliable from cgroups, checking:
  - /sys/fs/cgroup/cpu/cpu.cfs_period_us
  - /sys/fs/cgroup/cpu/cpu.cfs_quota_us
- How many memory available from cgroups, checking: /sys/fs/cgroup/memory/memory.limit_in_bytes 

**Additional context**

N/A

**Comment by hetao92** [comment]
merged
