### ISSUE TITLE
rpm install error

### ISSUE THREAD

**Issue by Roarain** [vesoft-inc/nebula-studio#230]
also tried nodejs node-v10.24.1-linux-x64 and node-v14.16.1-linux-x64
but faild...

```
# cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
# egrep node ~/.bash_profile
PATH=$PATH:$HOME/bin:/data/node-v10.16.3-linux-x64/bin/
# node --version
v10.16.3
# rpm -ivh nebula-graph-studio-2.1.9-1.x86_64.rpm
Preparing...                          ################################# [100%]
/var/tmp/rpm-tmp.8mdpQf: line 6: type: node: not found
Install failed for the reason: the nodejs(>v10.16.0) required
error: %pre(nebula-graph-studio-2.1.9-1.x86_64) scriptlet failed, exit status 1
error: nebula-graph-studio-2.1.9-1.x86_64: install failed
```

**Comment by Roarain** [comment]
according to doc 
https://github.com/nodejs/help/wiki/Installation#using-sudo-to-symlink-node-npm-and-npx-into-usrbin
must use `ln -s` to configure node ,so successed.

**Comment by Roarain** [comment]
install success but start faild.
```
# sh start.sh
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /usr/bin/npm:19:21
    at Object.<anonymous> (/usr/bin/npm:152:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[root@k8s-db-7 scripts]# 2021/04/14 17:38:11 --- START OF NEBULA IMPORTER ---
2021/04/14 17:38:11 [INFO] httpserver.go:80: Starting http server on 5699
2021/04/14 17:38:11.826 [I] [asm_amd64.s:1371]  http server Running on http://0.0.0.0:8080
```

**Comment by nianiaJR** [comment]
> install success but start faild.
> 
> ```
> # sh start.sh
> internal/modules/cjs/loader.js:638
>     throw err;
>     ^
> 
> Error: Cannot find module '../lib/utils/unsupported.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at /usr/bin/npm:19:21
>     at Object.<anonymous> (/usr/bin/npm:152:3)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> [root@k8s-db-7 scripts]# 2021/04/14 17:38:11 --- START OF NEBULA IMPORTER ---
> 2021/04/14 17:38:11 [INFO] httpserver.go:80: Starting http server on 5699
> 2021/04/14 17:38:11.826 [I] [asm_amd64.s:1371]  http server Running on http://0.0.0.0:8080
> ```

what are your system and version?

**Comment by wuyanxin** [comment]
`sudo ln -s /usr/local/nodejs/bin/* /usr/bin/`  is required
