### ISSUE TITLE
可视化显示错误

### ISSUE THREAD

**Issue by shutter-cp** [vesoft-inc/nebula-studio#249]
<img width="1535" alt="image" src="https://user-images.githubusercontent.com/37921589/177130670-c8317e34-6ca9-44f8-98bb-0de8fc9036c2.png">

查询出15条数据，可视化显示只有一条 而且无法拖动

nebula studio version:3.3.2
nebula version: 3.1

**Comment by hetao92** [comment]
1. Open the Chrome console to see if there is some error messages when rendering
2. Can you provide the unrendered data information?

**Comment by shutter-cp** [comment]
<img width="1767" alt="image" src="https://user-images.githubusercontent.com/37921589/177238174-fc886362-aba9-45f9-9cb4-8184998445df.png">
<img width="1955" alt="image" src="https://user-images.githubusercontent.com/37921589/177238242-e77f5268-c2cf-4427-b709-d909c2e975a6.png">

https://user-images.githubusercontent.com/37921589/177238440-a6f7dbc7-5c4b-4cb7-aaaa-ffa90cf048ef.mov

**Comment by hetao92** [comment]
got it, we will fix this in next version

**Comment by hetao92** [comment]
it has been fixed in studio v3.4.0 and released
