### ISSUE TITLE
Nebula Studio can't login

### ISSUE THREAD

**Issue by liuxiaocs7** [vesoft-inc/nebula-studio#251]
**Describe the bug (__must be provided__)**

Nebula Studio can't login

**Your Environments (__must be provided__)**

* OS: Linux
* Studio-version: 3.2.3

**How To Reproduce(__must be provided__)**

1. I depoly Nebula Graph and Nebula Studio by Docker.
2. I can access nebula by nebula console.
![image](https://user-images.githubusercontent.com/42756849/177315054-b1925679-b0e1-43d7-bf60-8aaa781ceda0.png)
3. But when I use nebula studio, I click the link button, I can't login and there's no any error message.
![login](https://user-images.githubusercontent.com/42756849/177316326-63d80941-c631-4a8d-9751-3370c63b29ba.gif)

I have restart the service but it doesn't seem to work.

**Comment by liuxiaocs7** [comment]
I try to use the version [3.3.2 nebula graph](https://docs.nebula-graph.com.cn/3.1.0/nebula-studio/deploy-connect/st-ug-deploy/#_12)，when i try to login, it shows:
![image](https://user-images.githubusercontent.com/42756849/177318172-f3cb3fb3-0233-4c7c-bc66-1d36486bd61b.png)
after restart nebula, it works.

**Comment by hetao92** [comment]
Please provide the nebula version and studio version used. and you can open chrome to check any messages, or if the interface returns data

**Comment by hetao92** [comment]
too many session created
you need to clear the nebula session manually or automatically after the session expires. Or modifying 'max_sessions_per_ip_per_user' in nebula-graphd.conf like the message suggests
refer to [doc](https://docs.nebula-graph.io/3.1.0/5.configurations-and-logs/1.configurations/3.graph-config/#session)

**Comment by liuxiaocs7** [comment]
Thanks.
