### ISSUE TITLE
Session release issues(suspect only)

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-studio#261]
Recently I encountered(together with other guys in the community) a couple of times that the default 300 sessions(per IP) exceeded in the studio.

Maybe it's caused by the studio backend(HTTP gw) not releasing sessions properly, or?

Thanks!

**Comment by hetao92** [comment]
it has been fixed in #183 with gateway(https://github.com/vesoft-inc/nebula-http-gateway/pull/98). So studio v3.3.x | v3.4.0 should not have this problem

**Comment by wey-gu** [comment]
> it has been fixed in #183 with gateway(https://github.com/vesoft-inc/nebula-http-gateway/pull/98). So studio v3.3.x | v3.4.0 should not have this problem

Thanks and sorry for not noticing an existing issue reporting this already.
