### ISSUE TITLE
Fail to install nebula-studio on Linux

### ISSUE THREAD

**Issue by bithw1** [vesoft-inc/nebula-studio#266]
I am following the instructions at https://docs.nebula-graph.com.cn/3.2.0/nebula-studio/deploy-connect/st-ug-deploy/
 to set up the nebula-studio 3.4 for Nebula graph 3.2.0.

I run the install with `root`.

[root@machine kg]# rpm -i nebula-graph-studio-3.4.0.x86_64.rpm --prefix=$(pwd)
**Start installing Nebula Studio now...
Nebula Studio has been installed.**
>>> /etc/sudoers.d/90-cloud-init-users: syntax error near line 17 <<<
sudo: parse error in /etc/sudoers.d/90-cloud-init-users near line 17
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
>>> /etc/sudoers.d/90-cloud-init-users: syntax error near line 17 <<<
sudo: parse error in /etc/sudoers.d/90-cloud-init-users near line 17
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
>>> /etc/sudoers.d/90-cloud-init-users: syntax error near line 17 <<<
sudo: parse error in /etc/sudoers.d/90-cloud-init-users near line 17
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
warning: %post(nebula-graph-studio-3.4.0-1.x86_64) scriptlet failed, exit status 1.

I  see the above error and warning information, and the graph studio is not started(port 7001 is not opened)

I would like to ask how to fix this problem, thanks.

**Comment by wey-gu** [comment]
should be related to start.sh assumed sudo could be used properly.


```
sudo systemctl daemon-reload && sudo systemctl enable nebula-graph-studio.service && sudo systemctl start nebula-graph-studio.service
```

Could you fix that by minimum verify with this command:

```
sudo ls
```

Ref https://superuser.com/questions/1345856/how-to-avoid-root-is-not-allowed-to-run-sudo

**Comment by wey-gu** [comment]
Or you could temporarily use a non-root sudo-able user to work this around.

**Comment by wey-gu** [comment]
Or you could run those script on systemctl without sudo, the installation should be done afterwards.

**Comment by bithw1** [comment]
Thanks @wey-gu for the helpful answer, I am able to work out, thanks a lot!

> should be related to start.sh assumed sudo could be used properly.
> 
> ```
> sudo systemctl daemon-reload && sudo systemctl enable nebula-graph-studio.service && sudo systemctl start nebula-graph-studio.service
> ```
> 
> Could you fix that by minimum verify with this command:
> 
> ```
> sudo ls
> ```
> 
> Ref https://superuser.com/questions/1345856/how-to-avoid-root-is-not-allowed-to-run-sudo
