### ISSUE TITLE
Unable to login nebula graph web ui(nebula studio)

### ISSUE THREAD

**Issue by bithw1** [vesoft-inc/nebula-studio#267]
Hi,

I successfully installed the nebula graph studio, and I am able to open the web ui at http://10.1.2.3:7001,
the login form appears, and I input the following information:
Host: 10.1.2.3
Username: root
Password: nebula

But I login failed with `ErrParam` message appears on the ui,

 I have no idea what happens, and would ask how to fix this problem ,thanks!

**Comment by bithw1** [comment]
The requested API : http://10.1.2.3:7001/api-nebula/db/connect

The response message is `{code: "40004001", message:"ErrParam"}`

**Comment by wey-gu** [comment]
the host part should be filled as host:port like "1.2.3.4:9669" 😊

**Comment by bithw1** [comment]
> the host part should be filled as host:port like "1.2.3.4:9669" 😊

Thanks @wey-gu for the helpful answer! it works for me now and I can play the graph web ui now, :-)

I would suggest that the Host input box choose `Host:Port` instead of Host.

**Comment by hetao92** [comment]
@bithw1 thanks for your suggestion. I will update placeholder in next version
