### ISSUE TITLE
misplaced "MIT" license declaration in package-lock.json

### ISSUE THREAD

**Issue by tian-zhong** [vesoft-inc/nebula-studio#269]
**Describe the bug (__must be provided__)**

package.json assert an "MIT" license while the project is supposed to be under apache-2.0.
original text
`{
  "name": "nebula-graph-studio",
  "version": "3.3.2",
  "lockfileVersion": 1,
  "requires": true,
  "packages": {
    "": {
      "name": "nebula-graph-studio",
      "version": "3.3.2",
      "license": "MIT",
      "dependencies": {`

correct code
`{
  "name": "nebula-graph-studio",
  "version": "3.3.2",
  "lockfileVersion": 1,
  "requires": true,
  "packages": {
    "": {
      "name": "nebula-graph-studio",
      "version": "3.3.2",
      "license": "Apache 2.0",
      "dependencies": {`

**Your Environments (__must be provided__)**

* OS: Linux,Mac or Windows
* Node-version: `node --version` 
* Studio-version: display in studio navBar

**How To Reproduce(__must be provided__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

Apache 2.0 license indicator should be used.

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by hetao92** [comment]
thanks. i wll update this in 3.4.1
