### ISSUE TITLE
What's the relationship between nebula explorer and nebula studio

### ISSUE THREAD

**Issue by bithw1** [vesoft-inc/nebula-studio#273]
Hi,

I am reading at https://docs.nebula-graph.com.cn/3.2.0/nebula-explorer/about-explorer/ex-ug-what-is-explorer/,

I am wondering the relationship between nebula explorer and nebula studio..

I searched the github repositiory at https://github.com/orgs/vesoft-inc/repositories?type=all
I only find the nebula studio there, does it mean that nebula explorer is not open sourced? Thanks!

**Comment by wey-gu** [comment]
Hi @bithw1,

Yes, the explorer is an enterprise-only product and it's a superset of studio :), with much more powerful features.

**Comment by bithw1** [comment]
Thanks @wey-gu for the quick response，I am closing this issue， thanks!
