### ISSUE TITLE
Studio UI blocked after uploading files

### ISSUE THREAD

**Issue by alan890104** [vesoft-inc/nebula-studio#274]
**Describe the bug (__must be provided__)**
After I import files to studio, my browser is blocked. I cannot perform any action other than close the browser.

**Your Environments (__must be provided__)**

* OS: Linux (Ubuntu 22.04.1 LTS)
* Node-version: v12.22.9
* Studio-version: 3.3.2
* Chrome-version: 104.0.5112.79 (64bits)

**How To Reproduce(__must be provided__)**

1. Click import button on navbar
2. press `Upload Files` link
3. Select multiple files
4. After uploading, the whole browser is blocked

**Expected behavior**

I am able to click any button on page, and I can switch to other tabs on browser

**Comment by hetao92** [comment]
could you please open the Chrome console to see if there is any error message

**Comment by alan890104** [comment]
The whole browser is blocked and I could not  perform any action such as F5 reload, F12 open console

**Comment by hetao92** [comment]
open it before you upload files. 
Btw, you can provide the file for us to test if it is convenient

**Comment by hetao92** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime. Thanks a lot for your contribution.
