### ISSUE TITLE
【Support】What JS/frontend frameworkd is used for nebula explorer and nebula studio?

### ISSUE THREAD

**Issue by bithw1** [vesoft-inc/nebula-studio#280]
Hi,

I would ask what  JS/frontend frameworkd is used for nebula explorer and nebula studio to perform graph view and editing?

Thanks!

**Comment by wey-gu** [comment]
I think d3.js was used for rendering in studio, and react was the framework.

@hetao92 correct me if wrong.

Explorer is not open source but react d3 was used, too. On top of that, NebulaGraph-veditor was used, too ;).

Please @hetao92 , @mizy add/ correct me :). 

Thanks.

**Comment by bithw1** [comment]
Thanks @wey-gu  for the helpful answer
