### ISSUE TITLE
studio source code compilation bug

### ISSUE THREAD

**Issue by XiaomuWang** [vesoft-inc/nebula-studio#281]
**Describe the bug (__must be provided__)**

When I install it, it shows successful login and can receive requests. But the webpage shows no page. What is the situation here?

**Your Environments (__must be provided__)**

* OS: Linux arm64
* Node-version: `node --version` 
* Studio-version: 3.3.2（ [3e171a5](https://github.com/vesoft-inc/nebula-studio/tree/v3.3.2)）

**How To Reproduce(__must be provided__)**

1. `npm install`
2. `npm run build`
3. `mv dist server/assets`
4. `cd server`
5. `vim config/example-config.yaml` (modify port)
6. `go build -o server`
7. ` ./server`( or `nohup ./server &`)

**Expected behavior**

I hope I can get the login interface of the studio

**Additional context**
![image](https://user-images.githubusercontent.com/46257486/186071853-1a05b876-4973-4f3e-b521-09d55ba9b3d5.png)
![image](https://user-images.githubusercontent.com/46257486/186071914-ae5fcc82-f87a-4cc4-94ce-7279ad5b785e.png)

**Comment by hetao92** [comment]
sorry, step 3 is wrong, please use `mv dist/* server/assets`
