### ISSUE TITLE
Is it available for commercialization scenarios？

### ISSUE THREAD

**Issue by wyw64962771** [vesoft-inc/nebula-studio#3]
When are you planning to add LICENSES?

**Comment by wey-gu** [comment]
Dear @wyw64962771,
We will do so @Sophie-Xie @nianiaJR.
And it should be aligned with Neubla Core Proejects' License, which is commercialization friendly, please @Sophie-Xie correct me if wrong.
Thanks.

**Comment by wyw64962771** [comment]
Thanks @wey-gu

**Comment by jerryliang64** [comment]
@hetao92 add the license as we talked about before.

**Comment by hetao92** [comment]
LICENSE has been added
