### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by leezea** [vesoft-inc/nebula-studio#310]
install by docker-compose
nebula-studio version is 2.0.0

when i create Schema in nebual stuido web,the error appears :client_1    | 2022/10/12 03:40:15 read tcp 172.20.0.3:56188->100.119.126.135:9669: i/o timeout
why?

**Comment by hetao92** [comment]
Which version of nebula are you using

**Comment by QingZ11** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
