### ISSUE TITLE
Make required ports like 7001 8080 and 5699 configurable.

### ISSUE THREAD

**Issue by CamusGao** [vesoft-inc/nebula-studio#32]
Make required ports like 7001 8080 and 5699 configurable please. Those ports are unavailable in my situation. /(ㄒoㄒ)/~~

**Comment by jerryliang64** [comment]
Ok，it's a useful suggestion, we'll make ports configurable in future.🤝  If you think it's necessary now, welcome to help
modify it😬

**Comment by hetao92** [comment]
#90, it will be released in v3.2.0
