### ISSUE TITLE
imprimitive type data: vertex/edge/path in map will crash the backend

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-studio#350]
**Describe the bug (__must be provided__)**

As title, minimal reproduce:

```
match (n:player) return {node: n}
```
or 
```
match p=(:player) return {p:p}
```
or
```
match ()-[e:follow]->() return {e:e} limit 10
```

**Your Environments (__must be provided__)**

* OS: Linux,Mac or Windows
* Node-version: `node --version` 
* Studio-version: display in studio navBar

**How To Reproduce(__must be provided__)**

1. Step 1, open console
2. Step 2, run `match (n:player) return {node: n}`

**Expected behavior**

no crash

**Comment by liangliangc** [comment]
已修复
