### ISSUE TITLE
display property problem

### ISSUE THREAD

**Issue by gkm0120** [vesoft-inc/nebula-studio#363]
**Is your feature request related to a problem? Please describe.**
In the process of using the official example, the returned result is to display vid, how to display the attribute? How to display the properties of vid name instead of displaying vid?
![image](https://user-images.githubusercontent.com/57723098/202968774-902f3812-b068-4b6e-9327-19dfd1de007f.png)

**Describe the solution you'd like**
I want to return the result as shown in the official README.md
![image](https://user-images.githubusercontent.com/57723098/202968950-c0f19bbe-2e4c-426a-a942-d51b8c42831c.png)

**Describe alternatives you've considered**
Does the official example use attributes as vid instead of its own vid? If you use your own vid, where should you find the configuration display?

**Additional context**
Thanks!

**Comment by hetao92** [comment]
The display attribute is not supported in the current version, and vid is displayed by default.
Btw, player name which is displayed in example is also its vid

**Comment by hetao92** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime. Thanks a lot for your understanding.
