### ISSUE TITLE
[QE]Parameterized statement-studio

### ISSUE THREAD

**Issue by Sophie-Xie** [vesoft-inc/nebula-studio#4]
The feature "Parameterized statement" in v2.6.0  will modify console, so studio need release.
Feature owner is @klay-ke

**Comment by jerryliang64** [comment]
More details about the release deadline？

**Comment by jerryliang64** [comment]
cc: @hetao92

**Comment by Sophie-Xie** [comment]
> More details about the release deadline？

v2.6 will release on 10.26.

**Comment by hetao92** [comment]
support in pr #69
