### ISSUE TITLE
I can not select one column in Select CSV Index

### ISSUE THREAD

**Issue by mingLiangShao** [vesoft-inc/nebula-studio#431]
**path:Map Vertices->Bind Datasource->vertices 1->Select CSV Index, I can not see bottom, tip me for “vertexId column index can't be null.”**

**Comment by hetao92** [comment]
Is there any error message in the browser console?

**Comment by hetao92** [comment]
May I ask if you deployed version 3.5.0 with docker, if yes, you can update to 3.5.1 or use other installation packages, such as rpm, tar

**Comment by QingZ11** [comment]
I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
