### ISSUE TITLE
Can't Be Fully Imported Data

### ISSUE THREAD

**Issue by arstian** [vesoft-inc/nebula-studio#46]
The data can't be fully imported even though the log already says that the data has been successfully imported without any errors/failed and the task is still running.

* OS: Linux
* Node-version: 10.19.0
* Studio-version: 3.0.0 and 3.1.0

How I imported the data: 
1. Create a schema name sales (vid type : fixed_string).
2. Create a tag name item (properties name/data type : id_single_item/string, region/string, country/string, item_type/string, sales_channel/string).
3. Create an edge name order (properties name/data type : order_id/string, id_item/string, unit_sold/string, unit_price/string, unit_cost/string, total_profit/string).
4. Go to import.
5. Select space : sales.
6. Upload files (item.csv and orderr.csv).
7. On map vertices, click add Bind Datasource (name : item.csv), then add tag vertexid : column 0, choose tag : item,  choose the CSV index. For id_single_item is column 0, region is column 1, country is column 2, item_type is column 3, sales_channel is column 4. All the type is string. 
8. on map edges, click add Bind Datasource (name : orderr.csv), for type : order, then mapping for srcid : column 1, dstid : column 1, order_id : column 0, id_item : column 1 , unit_sold : column 2, unit_price : column 3, unit_cost : column 4, total_profit : column 5.
9. Start import.

Expected:
The data can be fully imported and the task stop running when the log says that the data has been successfully imported without any errors/failed

**Comment by hetao92** [comment]
we will fix in next version. Thanks

**Comment by hetao92** [comment]
fixed in #100 ,will be released in next version v3.2.0
