### ISSUE TITLE
[可视化导入] 导入错误类型 引起服务挂掉

### ISSUE THREAD

**Issue by nebula-bots** [vesoft-inc/nebula-studio#462]
测试环境：http://192.168.8.131:7001/
登录host：192.168.8.185:9669
使用模板导入参数:
`
version: v2
description: studio import
removeTempFiles: null
clientSettings:
  retry: 3
  concurrency: 10
  channelBufferSize: 128
  space: Test
  connection:
    user: "root"
    password: "nebula"
    address: "192.168.8.185:9669,192.168.8.134:9669,192.168.8.186:9669"
  postStart: null
  preStop: null
logPath: import.log
workingDir: null
files:
- path: 所有数据类型.csv
  failDataPath: 所有数据类型.csv
  batchSize: 128
  limit: null
  inOrder: null
  type: csv
  csv:
    withHeader: true
    withLabel: false
    delimiter: ','
  schema:
    type: vertex
    edge: null
    vertex:
      vid:
        index: 0
        function: null
        type: string
        prefix: null
      tags:
      - name: 所有数据类型_qa
        props:
        - name: "1"
          type: int
          index: 1
        - name: "2"
          type: bool
          index: 5
        - name: "3"
          type: string
          index: 6
        - name: "4"
          type: string
          index: 0
        - name: "5"
          type: double
          index: 7
        - name: "6"
          type: int
          index: 2
        - name: "7"
          type: int
          index: 3
        - name: "8"
          type: int
          index: 4
        - name: "9"
          type: float
          index: 8
        - name: "10"
          type: date
          index: 9
        - name: "11"
          type: time
          index: 10

`
引发服务停止
![image](https://user-images.githubusercontent.com/102048716/218685152-42046345-9fc2-46b0-b8e1-eca4bcbe4a3e.png)

**Comment by hetao92** [comment]
This problem is caused by inaccurate withheader configuration and will be resolved when the importer is updated in the next version
