### ISSUE TITLE
[可视化报错]查询边时，自动执行 match（n） id（）in ["","" ... ""]   当条件集合节点超过 15个节点会报错

### ISSUE THREAD

**Issue by helomaki** [vesoft-inc/nebula-studio#467]
studio 版本 3.5.0
执行边查询结果 表格形式正常，但可视化报错 （当节点超过 一定数量 15 个时才报错）
如图：
![image](https://user-images.githubusercontent.com/24219594/219940418-90461307-636f-49d0-a1d5-8af7cc143c3a.png)
原因
可视化时自动请求的语句 match（n） 没有指定 具体tag
![image](https://user-images.githubusercontent.com/24219594/219940455-04991bd6-3d32-49b4-92e2-321715f9929a.png)
![image](https://user-images.githubusercontent.com/24219594/219940526-cb51719b-072f-41b5-8bde-4b48b727b96d.png)
如果改成 match(n:xxx) 即可

**Comment by helomaki** [comment]
![image](https://user-images.githubusercontent.com/24219594/219940705-27e4ca2b-1c04-46b7-b4e4-2365c04d9faf.png)

**Comment by hetao92** [comment]
指定 id 的情况下是不需要 limit 的，文档里的场景和这不一致。另外关于没有渲染出来的情况，可以看一下控制台有什么其他报错信息，还有，你查询出来的结果是悬挂边吗
<img width="750" alt="image" src="https://user-images.githubusercontent.com/18328704/220035532-e63e6ca3-39a1-4cff-a62d-acef33d205ce.png">

**Comment by QingZ11** [comment]
@helomaki 你的问题是不是和论坛这个帖子的情况是一致的？[https://discuss.nebula-graph.com.cn/t/topic/12208](https://discuss.nebula-graph.com.cn/t/topic/12208) ，是的话，它已经被确定个需要修复的 bug 了 cc @hetao92

**Comment by QingZ11** [comment]
这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。

谢谢你的反馈 😊
