### ISSUE TITLE
[欢迎页]demo语句报错

### ISSUE THREAD

**Issue by liangliangc** [vesoft-inc/nebula-studio#479]
demo_identity_resolution
demo_datalineage
两个spaces都会报错且错误内容一致
![image](https://user-images.githubusercontent.com/102048716/220580426-dc5cfa0a-b829-42ef-81ca-cabf3f130593.png)
![image](https://user-images.githubusercontent.com/102048716/220580496-795afd13-9e41-4629-81ab-b97a714c3bbc.png)

**Comment by wey-gu** [comment]
I'll remove this, sorry I was testing it in an old version of NebulaGraph, thus this [incompatibility fields](https://github.com/vesoft-inc/nebula/commit/49113e3ed4fe75d5d262603d8e2f6521d6d9b5f6#diff-711776cd91b90d1b96e50e9105c53ad158f35d6d09f87759abbd1889d2f46fae) was introduced.
