### ISSUE TITLE
[欢迎页]英文demo_datalineage介绍 报错404

### ISSUE THREAD

**Issue by liangliangc** [vesoft-inc/nebula-studio#481]
![image](https://user-images.githubusercontent.com/102048716/220584707-d6587c5e-6d28-48a1-82fd-759d309fa962.png)
![image](https://user-images.githubusercontent.com/102048716/220584744-77d75517-36dd-4096-a292-664fc8bd8ce1.png)

**Comment by wey-gu** [comment]
Orz...I'll do a redirect from siwei.io/en/en/data-lineage-oss-ref-solution/ for now, and fix it only in master later

**Comment by wey-gu** [comment]
Later https://siwei.io/en/en/data-lineage-oss-ref-solution/ will be redirect to https://siwei.io/en/data-lineage-oss-ref-solution/ (wait for Cloudflare cache expired), and @huaxiabuluo will help correct in his WIP pr, too.

Sorry again 🧎🏻~

**Comment by wey-gu** [comment]
close as fixed.
Thanks!
