### ISSUE TITLE
[多数据源导入] 前缀 后缀过长超出限制

### ISSUE THREAD

**Issue by nebula-bots** [vesoft-inc/nebula-studio#518]
![image](https://user-images.githubusercontent.com/102048716/229059393-f7237b2f-d69e-4aad-8f24-5bf94c636a4a.png)

**Comment by liangliangc** [comment]
修复后仍存在此问题
![image](https://user-images.githubusercontent.com/102048716/231078078-9cf5f37d-1028-4f20-93a9-cc9dd2a5b560.png)
