### ISSUE TITLE
/explore can store history 

### ISSUE THREAD

**Issue by jsvisa** [vesoft-inc/nebula-studio#52]
**Is your feature request related to a problem? Please describe.**

I am currently using NEBULA Studio at V3.0.0, and when my browser accidentally quits or hits refresh, the graphs generated by the original exploration are missing, which is great if you support saving history in browser in server.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jerryliang64** [comment]
Yes, it's really a good idea and we've been developing this feature in our [nebula-explorer](https://docs.nebula-graph.com.cn/2.5.1/nebula-explorer/about-explorer/ex-ug-what-is-explorer/)，you can try it in our next version release. But for studio, the functions about explorer will not be changed in future，it's duplicated with the explorer.🤝
