### ISSUE TITLE
The return value of the same statement studio and console are different

### ISSUE THREAD

**Issue by foesa-yang** [vesoft-inc/nebula-studio#53]
nebula version v2.5.0, the statement is as follows
```
RETURN range(0,5)[-12];
```
In console:
![lALPDg7mRlq3G5lrzQHc_476_107 png_720x720q90g](https://user-images.githubusercontent.com/35463247/130213898-c68098da-18a6-4db1-9595-267900b14ba2.jpg)
But in studio:
<img width="673" alt="截屏2021-08-20 下午5 40 36" src="https://user-images.githubusercontent.com/35463247/130214055-6a118843-b4f0-4d47-8f76-00700599e4c6.png">

**Comment by zhanghytc** [comment]
this is a bug of Nebula-studio,Nebula-Console  result is correct

**Comment by jerryliang64** [comment]
> this is a bug of Nebula-studio,Nebula-Console result is correct

Thanks，we will fix it in next release. Btw，welcome to fix it via pr

**Comment by hetao92** [comment]
fixed in gateway https://github.com/vesoft-inc/nebula-http-gateway/pull/60
and will publish in next release

**Comment by hetao92** [comment]
fixed in gateway https://github.com/vesoft-inc/nebula-http-gateway/pull/60
and will publish in next release
