### ISSUE TITLE
Improving Connecting Page fresh user experience

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-studio#54]
- [ ] Use the default user/password when clicking connect unfilled
- [ ] Rename the `Host` field to `GraphD Host: Port` or other things that make sense of this w/o reading docs, or provide hints

A couple of fresh users had been blocked in this phase as I know :).

**Comment by hetao92** [comment]
i will add placeholder in the host input box. As for more hints, I plan to add it in a better way in the next version of the UI revision
