### ISSUE TITLE
Display problem in explore

### ISSUE THREAD

**Issue by foesa-yang** [vesoft-inc/nebula-studio#55]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/35463247/144401832-0a873ca0-3d9a-4d6a-9aa2-df238800a2a6.png">

**Comment by jerryliang64** [comment]
Can you give a sample to reproduce this problem？

**Comment by foesa-yang** [comment]
On the Explore page, this will happen if you expand a vertex with self-loop.

**Comment by jerryliang64** [comment]
👌. Maybe it's about the render accurately. I'll label it and fix it in future.
