### ISSUE TITLE
blank chars is allowed at space name in creating a space.

### ISSUE THREAD

**Issue by CorvusYe** [vesoft-inc/nebula-studio#551]
Hello ~
**Describe the bug (__must be provided__)**

As title. I don't know it is a feature or a bug.

**Your Environments (__must be provided__)**
- Studio version: `v3.4.0`
- OS: Windows

**How To Reproduce(__must be provided__)**
![image](https://github.com/vesoft-inc/nebula-studio/assets/15630211/f812a28f-f17d-45e9-aafb-b1ed36e00eca)

**Additional context**
It's reported in https://github.com/nebula-contrib/ngbatis/issues/150

**Comment by wey-gu** [comment]
Aha, more like a.... feature?

```
(root@nebula) [(none)]> create space ` test `(vid_type = fixed_string(30));
Execution succeeded (time spent 2.117ms/107.990125ms)

Wed, 17 May 2023 16:24:57 CST

(root@nebula) [(none)]> use ` test `
[ERROR (-1005)]: SpaceNotFound: SpaceName ` test `

Wed, 17 May 2023 16:25:04 CST

(root@nebula) [(none)]> use `\ test\ `
Execution succeeded (time spent 1.05ms/24.459334ms)

Wed, 17 May 2023 16:25:10 CST
```
