### ISSUE TITLE
[查看Schema] 结果不正确

### ISSUE THREAD

**Issue by nebula-bots** [vesoft-inc/nebula-studio#552]
host：192.168.8.131:9669
图空间：Anti-money laundering
存在边的关系 但查看Schema展示不出来，之前是可以展示出来的
![image](https://github.com/vesoft-inc/nebula-explorer-ent/assets/102048716/e2cf7b7e-8e8a-47fa-9fda-fdc6f6f2e34b)
![image](https://github.com/vesoft-inc/nebula-explorer-ent/assets/102048716/cdbb3a1a-2725-4675-8c03-db326c48f22a)

**Comment by hetao92** [comment]
数据更新需要先重建索引，重建完即可查到数据
