### ISSUE TITLE
新建SFTP数据源,导入数据选择文件时报错

### ISSUE THREAD

**Issue by lgtianxiawudi** [vesoft-inc/nebula-studio#576]
**General Question**

![image](https://github.com/vesoft-inc/nebula/assets/3023666/e0789cbe-c626-4c33-b46c-dd37e329c9ed)
![image](https://github.com/vesoft-inc/nebula/assets/3023666/3a81cda1-5380-46eb-b2d0-cba783a42348)

**Comment by wey-gu** [comment]
This is related to NebulaGraph Studio, will move to the correct repo.

**Comment by wey-gu** [comment]
Thanks for reporting this @lgtianxiawudi .

I guess https://github.com/vesoft-inc/nebula-studio/pull/572 had fixed it already, would you mind deploying a master nightly build version of the studio to see if the issue keeps?

**Comment by lgtianxiawudi** [comment]
my version is [vesoft/nebula-graph-studio:v3.7.0](https://github.com/vesoft-inc/nebula-studio/issues/576#)

is thiis version?

**Comment by wey-gu** [comment]
> 

The fix happened after the v3.7.0 release :) i.e. if you deploy it via docker, you could change tag from v3.7.0 to [nightly](https://hub.docker.com/layers/vesoft/nebula-graph-studio/nightly/images/sha256-e7c14141046abefc258c38e17749c5ebac99197c80e478352463b70340d4554a?context=explore)

**Comment by lgtianxiawudi** [comment]
it's ok ,thank you help
