### ISSUE TITLE
Does nebula-studio support nginx 

### ISSUE THREAD

**Issue by bigdata-spec** [vesoft-inc/nebula-studio#585]
I have 3 nodes，
when I connect server I should choose one from 3, it work well.
![image](https://github.com/vesoft-inc/nebula-studio/assets/23710717/1b4cab50-c375-4f42-bdbd-c139584f2d10)

![image](https://github.com/vesoft-inc/nebula-studio/assets/23710717/78bc0721-38a6-493e-ba9a-74cfd39ccbb4)
I try use nginx
and set config like this:
![image](https://github.com/vesoft-inc/nebula-studio/assets/23710717/afa8c329-53ad-4853-a121-3492c8532587)

but I can't connect nebula.
how can I do ?
nebula version is 3.5 and studio is 3.2.5

**Comment by mizy** [comment]
> I have 3 nodes， when I connect server I should choose one from 3, it work well. ![image](https://user-images.githubusercontent.com/23710717/253900224-1b4cab50-c375-4f42-bdbd-c139584f2d10.png)
> 
> ![image](https://user-images.githubusercontent.com/23710717/253899721-78bc0721-38a6-493e-ba9a-74cfd39ccbb4.png) I try use nginx and set config like this: ![image](https://user-images.githubusercontent.com/23710717/253899977-afa8c329-53ad-4853-a121-3492c8532587.png)
> 
> but I can't connect nebula. how can I do ? nebula version is 3.5 and studio is 3.2.5

OK,you need a websocket proxy, cause the studio use webscoket to connect DB between browser and server.
maybe the nginx conf look like this:
```
location /nebula_ws {
    proxy_pass http://127.0.0.1:7001;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
}
```

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊

这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。

谢谢你的反馈 😊
