### ISSUE TITLE
欢迎页草图文案不正确

### ISSUE THREAD

**Issue by liangliangc** [vesoft-inc/nebula-studio#615]
<img width="1120" alt="566c244792cd487643a92dc564643c06" src="https://github.com/vesoft-inc/nebula-studio/assets/102048716/a4c84d38-04b5-47d1-9cad-b7c260d88866">

**Comment by slimshadylol0303** [comment]
您可以在画板上自行设计 Schema，直观展示点边关系
You can design your schemas on the canvas to visually display the relationships between vertices and edges.
