### ISSUE TITLE
Optimized query visualization

### ISSUE THREAD

**Issue by Sixkd** [vesoft-inc/nebula-studio#619]
**Is your feature request related to a problem? Please describe.**
in version 3.7.0
Graph overlaps also occur when the number of query nodes is not too large
<img width="312" alt="1692263432049" src="https://github.com/vesoft-inc/nebula-studio/assets/57515117/63bd24c3-cb2a-4652-be93-24139a5a3bab">

**Describe the solution you'd like**
Whether we can optimize the graphics display and drag some borders

**Comment by mizy** [comment]
> **Is your feature request related to a problem? Please describe.** in version 3.7.0 Graph overlaps also occur when the number of query nodes is not too large <img alt="1692263432049" width="312" src="https://user-images.githubusercontent.com/57515117/261259284-63bd24c3-cb2a-4652-be93-24139a5a3bab.png">
> 
> **Describe the solution you'd like** Whether we can optimize the graphics display and drag some borders

i try to fix the force layout in #626, maybe this makes it better
