### ISSUE TITLE
Config Server details

### ISSUE THREAD

**Issue by sunkararp** [vesoft-inc/nebula-studio#62]
- We installed Nebula graph
- We are able to connect, create spaces and execute queries using Python library
- We also installed nebula-studio using helm start
- Default 'Config Server' web page is prompting for following information
  - Host
  - Username
  - Password

Can someone provide documentation for 'Config Server' web page

**Comment by sunkararp** [comment]
Found this doc https://docs.nebula-graph.io/1.2.1/nebula-studio/install-configure/st-ug-connect/

When I used user and password (default); I'm getting 404 error.

**Comment by wey-gu** [comment]
Dear @sunkararp ,
Sorry for the late response, please check https://docs.nebula-graph.io/2.6.1/nebula-studio/deploy-connect/st-ug-connect/ , will that answer your question?
