### ISSUE TITLE
optimize the graph edge output overlap

### ISSUE THREAD

**Issue by Sixkd** [vesoft-inc/nebula-studio#629]
#619 #626 

**Describe the solution you'd like**
Under the current optimization #626 , several edges of the query will still appear in the case of line crossing
![image](https://github.com/vesoft-inc/nebula-studio/assets/57515117/2903c861-1d92-4a4f-a206-6755f52bd6cd)

**Describe alternatives you've considered**
Can we reduce the unnecessary crossing of edge

**Comment by mizy** [comment]
> #619 #626
> 
> **Describe the solution you'd like** Under the current optimization #626 , several edges of the query will still appear in the case of line crossing ![image](https://user-images.githubusercontent.com/57515117/263669510-2903c861-1d92-4a4f-a206-6755f52bd6cd.png)
> 
> **Describe alternatives you've considered** Can we reduce the unnecessary crossing of edge

em, looks like not a simple question, maybe you need drag the vertex by your self in this situation, and i will try to remake the force config someday

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊

这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。
