### ISSUE TITLE
Helm deployed Studio release-3.8 suffers from `config file etc/studio-api.yaml, field File.SqliteDbFilePath is not set`

### ISSUE THREAD

**Issue by qiuchen001** [vesoft-inc/nebula-studio#702]
Studio版本：release-3.8

复现步骤：

1. git clone https://github.com/vesoft-inc/nebula-studio.git
2. cd nebula-studio
3. helm upgrade --install my-studio --set service.type=NodePort --set service.port={30070} deployment/helm

现象：
pod将会报错，日志为：config file etc/studio-api.yaml, field File.SqliteDbFilePath is not set
对应的configmap为：
![a59d2c229bbd0bce34b0a503ff0b9c9](https://github.com/vesoft-inc/nebula-studio/assets/139746392/343c9ac5-4d5c-46f9-9769-23f8052d6dfb)

**Comment by huaxiabuluo** [comment]
> Studio版本：release-3.8
> 
> 复现步骤：
> 
> 1. git clone https://github.com/vesoft-inc/nebula-studio.git
> 2. cd nebula-studio
> 3. helm upgrade --install my-studio --set service.type=NodePort --set service.port={30070} deployment/helm
> 
> 现象： pod将会报错，日志为：config file etc/studio-api.yaml, field File.SqliteDbFilePath is not set 对应的configmap为： ![a59d2c229bbd0bce34b0a503ff0b9c9](https://private-user-images.githubusercontent.com/139746392/288971336-343c9ac5-4d5c-46f9-9769-23f8052d6dfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMTk4NjUsIm5iZiI6MTcwMjAxOTU2NSwicGF0aCI6Ii8xMzk3NDYzOTIvMjg4OTcxMzM2LTM0M2M5YWM1LTRkNWMtNDZmOS05NzY5LTIzZjgwNTJkNmRmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOFQwNzEyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGU0MDczZjNkMWU1NTA5MThiYzM3MzNjZWVmZmUyYTgxY2Q4NDg3ZjZhOTBkMzdhNjAyMGE2YjgwN2I4ZWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iA3qyLqI72fuG1Mt4SsvO-nUWdGQ5w3BFddLi4QBh_s)

看起来是比较早期某个版本的 mater 代码？

**Comment by nekomeowww** [comment]
> Pod 将会报错，日志为：`config file etc/studio-api.yaml, field File.SqliteDbFilePath is not set`

values.yaml 里面的镜像版本改过吗？`3.8` 的话应该没有这个错误了才对

```yaml
image:
  pullPolicy: IfNotPresent
  nebulaStudio:
    name: vesoft/nebula-graph-studio
    version: v3.8.0
```

`3.7` 确实是会有这样的问题：

https://github.com/vesoft-inc/nebula-studio/blob/b0e4f2474870feae96d5b8ada427afa78c22426d/server/api/studio/internal/config/config.go#L23-L28

另外图里面还在用 `Type: "mysql"`，如果是测试用的部署的话，应该得切换到 `sqlite3` 才能让它正常运作

**Comment by nekomeowww** [comment]
@qiuchen001 重新拉一下 git 仓库的更新，修改一下 

https://github.com/vesoft-inc/nebula-studio/blob/70a52ac9efa993e2e528f20a8cba4eda8ea085f5/deployment/helm/templates/configmap.yaml#L31-L32

的 Type 到 `sqlite3`

然后重新原地执行

```shell
helm install nebula-studio --namespace nebula .
```

应该就能用了。

记得部署之后的 Service 也检查一下，如果需要 NodePort 类型的 Service 需要直接访问的话可以用

```shell
kubectl expose <deployment> --name=<name> --type=NodePort
```

暴露一下。

cc @huaxiabuluo @wey-gu 应该可以关掉 Issue 了

**Comment by wey-gu** [comment]
太强了，感谢 @nekomeowww !!!
