### ISSUE TITLE
nebula-graph-studio linux centos7下安装报错了，npm run start error

### ISSUE THREAD

**Issue by yaoyuanyy** [vesoft-inc/nebula-studio#75]
nebula-graph-studio linux centos7下安装报错了

[root@VM nebula-graph-studio]# npm run start

> nebula-graph-studio@3.1.0 start
> egg-scripts start --daemon --title=egg-server-nebula-graph-studio --workers=3

[egg-scripts] Starting egg application at /root/software/nebula-gragh/nebula-graph-studio/nebula-graph-studio
[egg-scripts] Run node --no-deprecation --require /root/software/nebula-gragh/nebula-graph-studio/nebula-graph-studio/node_modules/source-map-support/register.js /root/software/nebula-gragh/nebula-graph-studio/nebula-graph-studio/node_modules/egg-scripts/lib/start-cluster {"title":"egg-server-nebula-graph-studio","workers":3,"baseDir":"/root/software/nebula-gragh/nebula-graph-studio/nebula-graph-studio","framework":"/root/software/nebula-gragh/nebula-graph-studio/nebula-graph-studio/node_modules/egg"} --title=egg-server-nebula-graph-studio
[egg-scripts] Save log file to /root/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] tail -n 100 /root/logs/master-stderr.log
[egg-scripts] Got error when startup:
[egg-scripts] Error: Package subpath './lib/request' is not defined by "exports" in /root/software/nebula-gragh/nebula-graph-studio/nebula-graph-studio/node_modules/koa/package.json
[egg-scripts]     at new NodeError (node:internal/errors:371:5)
[egg-scripts]     at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
[egg-scripts]     at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
[egg-scripts]     at resolveExports (node:internal/modules/cjs/loader:482:36)
[egg-scripts]     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
[egg-scripts]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
[egg-scripts]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[egg-scripts]     at Module.require (node:internal/modules/cjs/loader:999:19)
[egg-scripts]     at require (node:internal/modules/cjs/helpers:102:18)
[egg-scripts]     at Object.<anonymous> (/root/software/nebula-gragh/nebula-graph-studio/nebula-graph-studio/node_modules/egg-core/lib/loader/mixin/extend.js:8:12)
[egg-scripts]
[egg-scripts] Start got error, see /root/logs/master-stderr.log
[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.
[root@VM nebula-graph-studio]#

[root@VM nebula-graph-studio]# cat /root/logs/master-stderr.log
Error: Package subpath './lib/request' is not defined by "exports" in /root/software/nebula-gragh/nebula-graph-studio/nebula-graph-studio/node_modules/koa/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/software/nebula-gragh/nebula-graph-studio/nebula-graph-studio/node_modules/egg-core/lib/loader/mixin/extend.js:8:12)

**Comment by wey-gu** [comment]
您的 `node`版本是多少哈？ 可以装一个 12 的版本
