### ISSUE TITLE
Very bad contrast on GQL query shown in studio console

### ISSUE THREAD

**Issue by johnny-smitherson** [vesoft-inc/nebula-studio#770]
**Describe the bug (__must be provided__)**

<img width="496" alt="beforeCapture" src="https://github.com/vesoft-inc/nebula-studio/assets/127537716/6e629738-d6e4-42b2-bcc5-c68d83d1f6ca">

green on green makes my eyes hurt

<img width="779" alt="Cap222ture" src="https://github.com/vesoft-inc/nebula-studio/assets/127537716/af451aa9-d8ad-4e80-bb6b-9e12c7c8e483">

cannot read these without selecting text in browser

**Your Environments (__must be provided__)**

* OS: Windows 10
* Node-version: `docker nebula-graph-studio:v3.9.1`
* Studio-version: v3.9.1
* Seen both in Firefox and Chrome

**How To Reproduce(__must be provided__)**

1. Run some console queries
2. Refresh page
3. Try to read older queries
4. bad contrast green on green

<img width="915" alt="Captur2e" src="https://github.com/vesoft-inc/nebula-studio/assets/127537716/baa1b668-ceb3-446d-b119-777e0de17b1a">

**Expected behavior**

Good contrast, for example after editing in DevConsole with `color:#111`:

<img width="572" alt="afterCapture" src="https://github.com/vesoft-inc/nebula-studio/assets/127537716/81b53552-4ee5-4f69-82bd-fa9117f5baac">

**Additional context**

proposed CSS changes:
- `color: #111`
- `font-family: monospaced`

**Comment by huaxiabuluo** [comment]
@yyh0808

**Comment by yyh0808** [comment]
Thank you very much for your detailed suggestions! 

Regarding colors and fonts, I completely agree with changing the style to a mono font. We originally also hoped to use a mono font for a better development experience. 

After using the mono font, the issue of colors being hard to read will improve significantly. However, since you mentioned that the colors still seem a bit painful, we will take your advice and deepen the font color to make the code look more comfortable. 

Thank you again for your enthusiastic and detailed suggestions.

**Comment by johnny-smitherson** [comment]
After discussion in https://github.com/vesoft-inc/nebula-studio/pull/771 it seems the root cause might be the combination between:
-  the Success/Failure design language (where color is 90% of the message information, e.g. "Sucecess" / "Fail", and where the product has its design guidelines to make it visually consistent) 
- the SQL where the the dots and dashes and syntax highlight colors of the code itself are relevant (and where the programmer is used to design guidelines for code, such as colored, monospace font, high contrast, white background).

I believe this combination does not work in this context. Here are my suggestions, courtesy of mspaint.exe

<img width="638" alt="309706714-6d51e187-edeb-457d-8785-e6ea7f947d46" src="https://github.com/vesoft-inc/nebula-studio/assets/127537716/3198f03d-5342-4511-902e-4ec881b19358">
<img width="638" alt="309706445-d814fad9-d98e-4106-b0d5-5a47dcb6ddf3" src="https://github.com/vesoft-inc/nebula-studio/assets/127537716/5681f5af-f4c4-4936-b32f-5537ed680a5a">

---

Also works with the grey background "can't type into this box" shade:

<img width="638" alt="309706714-6d51e187-edeb-457d-8785-e6ea7f947d46" src="https://github.com/vesoft-inc/nebula-studio/assets/127537716/3165ecd1-bc32-4400-b218-716ec5ae47c6">
<img width="638" alt="309706445-d814fad9-d98e-4106-b0d5-5a47dcb6ddf3" src="https://github.com/vesoft-inc/nebula-studio/assets/127537716/966bc026-8937-4339-9587-a29afcd85507">

---

Good luck!
