### ISSUE TITLE
V3.10版本使用域名访问Websocket URL is empty

### ISSUE THREAD

**Issue by weishengmin** [vesoft-inc/nebula-studio#807]
我的部署方式采用DEB 部署 Studio，版本v3.10
当我使用ip的方式访问studio时，功能都正常
当我使用域名访问studio时，点击schame或者console等功能都会出现Websocket URL is empty的错误

**Comment by bingerZhang** [comment]
请教下域名访问下这个问题原因是什么？怎么解决的 @weishengmin

**Comment by weishengmin** [comment]
nginx解析加上Websocket @bingerZhang
