### ISSUE TITLE
support multiple types of data sources in the studio

### ISSUE THREAD

**Issue by handsonbao** [vesoft-inc/nebula-studio#82]
**Is your feature request related to a problem? Please describe.**
When i want to load data by studio, i can only use .csv files. 
If I have some other types of data sources, such as hive and spark. It will be a very complicated thing.

**Describe the solution you'd like**
Maybe we can set a "data source management" in the studio, so that we can do some config and load data visually. 

**Describe alternatives you've considered**
manually config in the terminal.

**Additional context**

**Comment by hetao92** [comment]
Thanks for your suggestion, we are planning to add support for multiple data sources and will support it in subsequent versions
