### ISSUE TITLE
support some commonly used nGQL in the "console"

### ISSUE THREAD

**Issue by handsonbao** [vesoft-inc/nebula-studio#84]
**Is your feature request related to a problem? Please describe.**
When i use nebula in the beginning, i can't remember all the nGQL. It will be great if there are some commonly used nGQL in the "console".

**Describe the solution you'd like**
We can save some commonly used nGQL in the "console", such as "show jobs" and "SUBMIT JOB COMPACT".
Or just design them as a button. 

**Describe alternatives you've considered**
Turn to the docs and search.

**Additional context**

**Comment by hetao92** [comment]
Supported by favorites function
